# Generated by Django 5.1 on 2024-08-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toys',
            old_name='discription',
            new_name='description',
        ),
    ]
