# Generated by Django 5.1 on 2024-08-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0003_rename_toys_toy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='toy_category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
